# Generated by Django 5.2.7 on 2025-12-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='ends_at',
            field=models.DateTimeField(),
        ),
    ]
