# Generated by Django 5.2.7 on 2025-12-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_savedauctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='is_active',
        ),
    ]
